### ISSUE TITLE
email processor error

### ISSUE THREAD

**Issue by NataliaErmolova** [InnovativeTravel/email-processor#3]
Follow instruction I did:  $ pip install git+https://github.com/InnovativeTravel/email-processor

all went successfully 

but when i try to do simple emailprocessor --help

getting an error: 

Georges-MBP:~ Valentina$ emailprocessor --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/emailprocessor", line 11, in <module>
    load_entry_point('emailprocessor==0.1', 'console_scripts', 'emailprocessor')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/emailprocessor/__init__.py", line 19
    class EmailProcessor(metaclass=abc.ABCMeta):
                                  ^
SyntaxError: invalid syntax

Any help would be appreciated

**Comment by raam86** [comment]
Try using python 3
